// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: artefacts.sql

package sqlcgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const commitArtefact = `-- name: CommitArtefact :one
UPDATE artefacts SET
    state = 'COMMITTED',
    plaintext_sha256 = $3,
    plaintext_size_bytes = $4,
    stored_sha256 = $5,
    stored_size_bytes = $6,
    commit_call_id = $7,
    committed_at = $8,
    retain_until = $9
WHERE id = $1 AND tenant = $2 AND state = 'PENDING'
RETURNING id, tenant, run_id, object_key, state, clearance, compartments, media_type, label, tool_fqn, created_by, begin_call_id, commit_call_id, codec, kek_id, wrapped_dek, plaintext_sha256, plaintext_size_bytes, stored_sha256, stored_size_bytes, retention_seconds, created_at, upload_expires_at, committed_at, retain_until, shredded_at
`

type CommitArtefactParams struct {
	ID                 string
	Tenant             string
	PlaintextSha256    string
	PlaintextSizeBytes int64
	StoredSha256       string
	StoredSizeBytes    int64
	CommitCallID       string
	CommittedAt        pgtype.Timestamptz
	RetainUntil        pgtype.Timestamptz
}

// Conditional on the state it requires, so a commit racing a sweep either
// wins or changes no rows and says so. A re-commit of an already committed
// artefact matches nothing here; the service reads the row back and treats an
// identical digest as the same commit.
func (q *Queries) CommitArtefact(ctx context.Context, arg CommitArtefactParams) (Artefact, error) {
	row := q.db.QueryRow(ctx, commitArtefact,
		arg.ID,
		arg.Tenant,
		arg.PlaintextSha256,
		arg.PlaintextSizeBytes,
		arg.StoredSha256,
		arg.StoredSizeBytes,
		arg.CommitCallID,
		arg.CommittedAt,
		arg.RetainUntil,
	)
	var i Artefact
	err := row.Scan(
		&i.ID,
		&i.Tenant,
		&i.RunID,
		&i.ObjectKey,
		&i.State,
		&i.Clearance,
		&i.Compartments,
		&i.MediaType,
		&i.Label,
		&i.ToolFqn,
		&i.CreatedBy,
		&i.BeginCallID,
		&i.CommitCallID,
		&i.Codec,
		&i.KekID,
		&i.WrappedDek,
		&i.PlaintextSha256,
		&i.PlaintextSizeBytes,
		&i.StoredSha256,
		&i.StoredSizeBytes,
		&i.RetentionSeconds,
		&i.CreatedAt,
		&i.UploadExpiresAt,
		&i.CommittedAt,
		&i.RetainUntil,
		&i.ShreddedAt,
	)
	return i, err
}

const deletePending = `-- name: DeletePending :exec
DELETE FROM artefacts WHERE id = $1 AND state = 'PENDING'
`

// The only DELETE in this service, and it removes a row that was never
// committed: an artefact nobody confirmed bytes for is a name and nothing
// else, so there is no fact for an audit trail to keep.
func (q *Queries) DeletePending(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, deletePending, id)
	return err
}

const disclosuresOf = `-- name: DisclosuresOf :many
SELECT seq, artefact_id, at, tenant, subject, call_id, clearance, compartments, url_expires_at, key_released FROM disclosures WHERE artefact_id = $1 ORDER BY seq
`

func (q *Queries) DisclosuresOf(ctx context.Context, artefactID string) ([]Disclosure, error) {
	rows, err := q.db.Query(ctx, disclosuresOf, artefactID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Disclosure
	for rows.Next() {
		var i Disclosure
		if err := rows.Scan(
			&i.Seq,
			&i.ArtefactID,
			&i.At,
			&i.Tenant,
			&i.Subject,
			&i.CallID,
			&i.Clearance,
			&i.Compartments,
			&i.UrlExpiresAt,
			&i.KeyReleased,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const expiredPending = `-- name: ExpiredPending :many
SELECT id, tenant, run_id, object_key, state, clearance, compartments, media_type, label, tool_fqn, created_by, begin_call_id, commit_call_id, codec, kek_id, wrapped_dek, plaintext_sha256, plaintext_size_bytes, stored_sha256, stored_size_bytes, retention_seconds, created_at, upload_expires_at, committed_at, retain_until, shredded_at FROM artefacts
WHERE state = 'PENDING' AND upload_expires_at < $1
ORDER BY upload_expires_at
LIMIT $2
`

type ExpiredPendingParams struct {
	UploadExpiresAt pgtype.Timestamptz
	Limit           int32
}

// Orphans: a begin_write whose presigned PUT has lapsed with no commit.
func (q *Queries) ExpiredPending(ctx context.Context, arg ExpiredPendingParams) ([]Artefact, error) {
	rows, err := q.db.Query(ctx, expiredPending, arg.UploadExpiresAt, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Artefact
	for rows.Next() {
		var i Artefact
		if err := rows.Scan(
			&i.ID,
			&i.Tenant,
			&i.RunID,
			&i.ObjectKey,
			&i.State,
			&i.Clearance,
			&i.Compartments,
			&i.MediaType,
			&i.Label,
			&i.ToolFqn,
			&i.CreatedBy,
			&i.BeginCallID,
			&i.CommitCallID,
			&i.Codec,
			&i.KekID,
			&i.WrappedDek,
			&i.PlaintextSha256,
			&i.PlaintextSizeBytes,
			&i.StoredSha256,
			&i.StoredSizeBytes,
			&i.RetentionSeconds,
			&i.CreatedAt,
			&i.UploadExpiresAt,
			&i.CommittedAt,
			&i.RetainUntil,
			&i.ShreddedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const expiredRetention = `-- name: ExpiredRetention :many
SELECT id, tenant, run_id, object_key, state, clearance, compartments, media_type, label, tool_fqn, created_by, begin_call_id, commit_call_id, codec, kek_id, wrapped_dek, plaintext_sha256, plaintext_size_bytes, stored_sha256, stored_size_bytes, retention_seconds, created_at, upload_expires_at, committed_at, retain_until, shredded_at FROM artefacts
WHERE state = 'COMMITTED' AND retain_until < $1
ORDER BY retain_until
LIMIT $2
`

type ExpiredRetentionParams struct {
	RetainUntil pgtype.Timestamptz
	Limit       int32
}

// Artefacts that have outlived the retention their creating tool declared.
func (q *Queries) ExpiredRetention(ctx context.Context, arg ExpiredRetentionParams) ([]Artefact, error) {
	rows, err := q.db.Query(ctx, expiredRetention, arg.RetainUntil, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Artefact
	for rows.Next() {
		var i Artefact
		if err := rows.Scan(
			&i.ID,
			&i.Tenant,
			&i.RunID,
			&i.ObjectKey,
			&i.State,
			&i.Clearance,
			&i.Compartments,
			&i.MediaType,
			&i.Label,
			&i.ToolFqn,
			&i.CreatedBy,
			&i.BeginCallID,
			&i.CommitCallID,
			&i.Codec,
			&i.KekID,
			&i.WrappedDek,
			&i.PlaintextSha256,
			&i.PlaintextSizeBytes,
			&i.StoredSha256,
			&i.StoredSizeBytes,
			&i.RetentionSeconds,
			&i.CreatedAt,
			&i.UploadExpiresAt,
			&i.CommittedAt,
			&i.RetainUntil,
			&i.ShreddedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getArtefact = `-- name: GetArtefact :one
SELECT id, tenant, run_id, object_key, state, clearance, compartments, media_type, label, tool_fqn, created_by, begin_call_id, commit_call_id, codec, kek_id, wrapped_dek, plaintext_sha256, plaintext_size_bytes, stored_sha256, stored_size_bytes, retention_seconds, created_at, upload_expires_at, committed_at, retain_until, shredded_at FROM artefacts WHERE id = $1 AND tenant = $2
`

type GetArtefactParams struct {
	ID     string
	Tenant string
}

// By id AND tenant, always. A row of another tenant answers no rows, which
// the service reports as "no such artefact" — the same answer an id that
// never existed gets, so a caller cannot map out another tenant's ids.
func (q *Queries) GetArtefact(ctx context.Context, arg GetArtefactParams) (Artefact, error) {
	row := q.db.QueryRow(ctx, getArtefact, arg.ID, arg.Tenant)
	var i Artefact
	err := row.Scan(
		&i.ID,
		&i.Tenant,
		&i.RunID,
		&i.ObjectKey,
		&i.State,
		&i.Clearance,
		&i.Compartments,
		&i.MediaType,
		&i.Label,
		&i.ToolFqn,
		&i.CreatedBy,
		&i.BeginCallID,
		&i.CommitCallID,
		&i.Codec,
		&i.KekID,
		&i.WrappedDek,
		&i.PlaintextSha256,
		&i.PlaintextSizeBytes,
		&i.StoredSha256,
		&i.StoredSizeBytes,
		&i.RetentionSeconds,
		&i.CreatedAt,
		&i.UploadExpiresAt,
		&i.CommittedAt,
		&i.RetainUntil,
		&i.ShreddedAt,
	)
	return i, err
}

const insertDisclosure = `-- name: InsertDisclosure :one
INSERT INTO disclosures (
    artefact_id, at, tenant, subject, call_id,
    clearance, compartments, url_expires_at, key_released
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
RETURNING seq, artefact_id, at, tenant, subject, call_id, clearance, compartments, url_expires_at, key_released
`

type InsertDisclosureParams struct {
	ArtefactID   string
	At           pgtype.Timestamptz
	Tenant       string
	Subject      string
	CallID       string
	Clearance    string
	Compartments []string
	UrlExpiresAt pgtype.Timestamptz
	KeyReleased  bool
}

// Written before the URL exists. A disclosure that cannot be recorded is a
// URL that is not minted.
func (q *Queries) InsertDisclosure(ctx context.Context, arg InsertDisclosureParams) (Disclosure, error) {
	row := q.db.QueryRow(ctx, insertDisclosure,
		arg.ArtefactID,
		arg.At,
		arg.Tenant,
		arg.Subject,
		arg.CallID,
		arg.Clearance,
		arg.Compartments,
		arg.UrlExpiresAt,
		arg.KeyReleased,
	)
	var i Disclosure
	err := row.Scan(
		&i.Seq,
		&i.ArtefactID,
		&i.At,
		&i.Tenant,
		&i.Subject,
		&i.CallID,
		&i.Clearance,
		&i.Compartments,
		&i.UrlExpiresAt,
		&i.KeyReleased,
	)
	return i, err
}

const insertPending = `-- name: InsertPending :one

INSERT INTO artefacts (
    id, tenant, run_id, object_key, state,
    clearance, compartments, media_type, label,
    tool_fqn, created_by, begin_call_id,
    codec, kek_id, wrapped_dek,
    retention_seconds, created_at, upload_expires_at
) VALUES (
    $1, $2, $3, $4, 'PENDING',
    $5, $6, $7, $8,
    $9, $10, $11,
    $12, $13, $14,
    $15, $16, $17
)
RETURNING id, tenant, run_id, object_key, state, clearance, compartments, media_type, label, tool_fqn, created_by, begin_call_id, commit_call_id, codec, kek_id, wrapped_dek, plaintext_sha256, plaintext_size_bytes, stored_sha256, stored_size_bytes, retention_seconds, created_at, upload_expires_at, committed_at, retain_until, shredded_at
`

type InsertPendingParams struct {
	ID               string
	Tenant           string
	RunID            string
	ObjectKey        string
	Clearance        string
	Compartments     []string
	MediaType        string
	Label            string
	ToolFqn          string
	CreatedBy        string
	BeginCallID      string
	Codec            string
	KekID            string
	WrappedDek       []byte
	RetentionSeconds int64
	CreatedAt        pgtype.Timestamptz
	UploadExpiresAt  pgtype.Timestamptz
}

// Every query this service runs, named, checked against the schema the
// migrations produce, and STATIC.
//
// Nothing here is built at run time. Values can be parameterised; identifiers
// cannot — no SQL dialect binds a column name, a table name or a sort
// direction — so a builder that takes `OrderBy(req.SortBy)` is not safer than
// concatenation, it only looks it. The combinations this service needs are
// small and closed, so they are enumerated as named queries and there is no
// injection surface at all rather than a guarded one. `TestEveryQueryIsAConstant`
// asserts that nothing in this package assembles SQL.
func (q *Queries) InsertPending(ctx context.Context, arg InsertPendingParams) (Artefact, error) {
	row := q.db.QueryRow(ctx, insertPending,
		arg.ID,
		arg.Tenant,
		arg.RunID,
		arg.ObjectKey,
		arg.Clearance,
		arg.Compartments,
		arg.MediaType,
		arg.Label,
		arg.ToolFqn,
		arg.CreatedBy,
		arg.BeginCallID,
		arg.Codec,
		arg.KekID,
		arg.WrappedDek,
		arg.RetentionSeconds,
		arg.CreatedAt,
		arg.UploadExpiresAt,
	)
	var i Artefact
	err := row.Scan(
		&i.ID,
		&i.Tenant,
		&i.RunID,
		&i.ObjectKey,
		&i.State,
		&i.Clearance,
		&i.Compartments,
		&i.MediaType,
		&i.Label,
		&i.ToolFqn,
		&i.CreatedBy,
		&i.BeginCallID,
		&i.CommitCallID,
		&i.Codec,
		&i.KekID,
		&i.WrappedDek,
		&i.PlaintextSha256,
		&i.PlaintextSizeBytes,
		&i.StoredSha256,
		&i.StoredSizeBytes,
		&i.RetentionSeconds,
		&i.CreatedAt,
		&i.UploadExpiresAt,
		&i.CommittedAt,
		&i.RetainUntil,
		&i.ShreddedAt,
	)
	return i, err
}

const shredArtefact = `-- name: ShredArtefact :one
UPDATE artefacts SET
    state = 'SHREDDED',
    wrapped_dek = NULL,
    shredded_at = $2
WHERE id = $1 AND state <> 'SHREDDED'
RETURNING id, tenant, run_id, object_key, state, clearance, compartments, media_type, label, tool_fqn, created_by, begin_call_id, commit_call_id, codec, kek_id, wrapped_dek, plaintext_sha256, plaintext_size_bytes, stored_sha256, stored_size_bytes, retention_seconds, created_at, upload_expires_at, committed_at, retain_until, shredded_at
`

type ShredArtefactParams struct {
	ID         string
	ShreddedAt pgtype.Timestamptz
}

// Crypto-shredding: the key goes, the row stays. `wrapped_dek = NULL` is what
// makes the payload unreadable under a real codec; the object is deleted
// separately, which is what makes it unreadable under the null one.
func (q *Queries) ShredArtefact(ctx context.Context, arg ShredArtefactParams) (Artefact, error) {
	row := q.db.QueryRow(ctx, shredArtefact, arg.ID, arg.ShreddedAt)
	var i Artefact
	err := row.Scan(
		&i.ID,
		&i.Tenant,
		&i.RunID,
		&i.ObjectKey,
		&i.State,
		&i.Clearance,
		&i.Compartments,
		&i.MediaType,
		&i.Label,
		&i.ToolFqn,
		&i.CreatedBy,
		&i.BeginCallID,
		&i.CommitCallID,
		&i.Codec,
		&i.KekID,
		&i.WrappedDek,
		&i.PlaintextSha256,
		&i.PlaintextSizeBytes,
		&i.StoredSha256,
		&i.StoredSizeBytes,
		&i.RetentionSeconds,
		&i.CreatedAt,
		&i.UploadExpiresAt,
		&i.CommittedAt,
		&i.RetainUntil,
		&i.ShreddedAt,
	)
	return i, err
}
