// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlcgen

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Artefact struct {
	ID                 string
	Tenant             string
	RunID              string
	ObjectKey          string
	State              string
	Clearance          string
	Compartments       []string
	MediaType          string
	Label              string
	ToolFqn            string
	CreatedBy          string
	BeginCallID        string
	CommitCallID       string
	Codec              string
	KekID              string
	WrappedDek         []byte
	PlaintextSha256    string
	PlaintextSizeBytes int64
	StoredSha256       string
	StoredSizeBytes    int64
	RetentionSeconds   int64
	CreatedAt          pgtype.Timestamptz
	UploadExpiresAt    pgtype.Timestamptz
	CommittedAt        pgtype.Timestamptz
	RetainUntil        pgtype.Timestamptz
	ShreddedAt         pgtype.Timestamptz
}

type Disclosure struct {
	Seq          int64
	ArtefactID   string
	At           pgtype.Timestamptz
	Tenant       string
	Subject      string
	CallID       string
	Clearance    string
	Compartments []string
	UrlExpiresAt pgtype.Timestamptz
	KeyReleased  bool
}
